version: '3.6'
networks:
  internal-net:
   name: workbench_subnet
services:

  backend:
    image: openjdk:11.0.1
    depends_on:
      - db
    environment:
      - DATABASE_ADDRESS=db
    container_name: backend
    networks:
      - internal-net
    volumes:
      - ./build/libs:/opt/
    command: java -jar /opt/backend-0.0.1.jar

  db:
    image: postgres:11.1
    container_name: db
    restart: always
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - internal-net
