version: '3.6'
networks:
  internal-net:
   name: workbench_subnet
services:

  proxy:
    image: nginx:1.15.8-alpine
    depends_on:
      - chess-backend
    container_name: proxy
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx:ro
    environment:
      - NGINX_HOST=ninrod.org
      - NGINX_PORT=80
    networks:
      - internal-net

  chess-backend:
    image: openjdk:11.0.1
    depends_on:
      - db
    container_name: backend
    networks:
      - internal-net
    volumes:
      - ./backend/build/libs:/opt/
    command: java -jar /opt/backend-0.0.1.jar

  db:
    image: postgres:11.1
    container_name: db
    restart: always
    volumes:
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - internal-net
